### PR TITLE
Add keymap.el to generate keyap asset from Agda emacs-mode

### PR DESCRIPTION
**Pull request by erydo**
The script loads `agda-mode.el` and generates both a JSON and JavaScript keymap/query file.

This removes the need for a hand-edited/extracted copy of Emacs agda-mode source, which makes it easier to keep up-to-date with the original mappings.
Additionally this includes the inherited mappings from `latin-ltx` without need for copying them.

The script can be run with `npm run keymap-gen`, or run with custom arguments like so:

```
./keymap.el generate --agda-emacs-mode-dir ~/Code/agda/src/data/emacs-mode
```

### CODE REVIEW

**Comment by erydo** [comment]
By the way @banacorn — if this isn't an approach you like, that's fine! Just figured I'd submit the PR since I was hacking at this just out of interest related to agda/agda#4104. I was curious how to pull the "actual" mappings out, rather than copying them and re-generating them. It would be nice to package/consolidate these somehow so they could be used with e.g derekelkins/agda-vim#45

**Comment by banacorn** [comment]
Thank you for the PR ❤️❤️❤️

The current keymap was generated using [this].(https://github.com/banacorn/keymap). It inherits mappings from both `agda-input.el`, `latin-ltx.el` and some user-configurable extensions. 

I'm not sure if they are actually doing the same thing (pardon my Lisp illiteracy XD).
But it's a really nice thing to have anyway!!

**Comment by erydo** [comment]
Yep, I saw that repo! For some reason couldn't find the link when I put up this PR, sorry…

The main reason I didn't use that was that its version of the files like [`agda-input.el`](https://github.com/banacorn/keymap/blob/16843d58124aff78e214ab1f77e43df9fdebce47/assets/agda-input.el) are not actually the same as the ["real" upstream ones](https://github.com/agda/agda/blob/29836b03cfd7779b22b6cb186b0a8a0147bc3487/src/data/emacs-mode/agda-input.el). They require being hand-edited to extract portions of the key mapping code. And e.g. its version of `latin-ltx.el` in particular would require heavy editing, since the upstream definition [uses several computed bindings](https://github.com/emacs-mirror/emacs/blob/d0e2a341dd9a9a365fd311748df024ecb25b70ec/lisp/leim/quail/latin-ltx.el#L207-L218). Also all of [the extensions](https://github.com/banacorn/keymap/blob/16843d58124aff78e214ab1f77e43df9fdebce47/assets/alpha-numeric.ext) had already been incorporated into the main `agda-input.el`, which has gone through a lot of additions over the past few years.

This script loads the actual shipped ELisp modules and dumps the mappings as interpreted by Emacs/Quail, so that the definitions are faithful to the upstream sources of truth. It would definitely be pretty easy to add a hook for further customization by users.

**Comment by banacorn** [comment]
Cool!

**Pull request merged**
